#ifndef CALCULATOR_CORE_EXPRESSION_BIN_EXPR_TREE_COMPONENTS_ASSOCIATIVITY_H_
#define CALCULATOR_CORE_EXPRESSION_BIN_EXPR_TREE_COMPONENTS_ASSOCIATIVITY_H_

enum class Associativity {
  LEFT,
  RIGHT
};

#endif  // CALCULATOR_CORE_EXPRESSION_BIN_EXPR_TREE_COMPONENTS_ASSOCIATIVITY_H_
